# 容器配置
server:
  port: 8080
#  tomcat:
#    uri-encoding: utf-8

# 配置数据库
spring:
  datasource:
    username: root
    password: Az789@At
    url: jdbc:mysql://localhost:3306/rework_demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

# mybatis
mybatis:
  mapper-locations: classpath:/c/*.xml
  configuration:
    map-underscore-to-camel-case: true # 驼峰自动转换
  #指定entity扫描包类让mybatis自定扫描到自定义的entity。
  type-aliases-package: com.example.demo.entity

# 日志等级
logging:
  level:
    com.example.demo.mapper: debug
