# 容器配置
server:
  port: 8080
#  tomcat:
#    uri-encoding: utf-8

# 配置数据库

# 日志等级
logging:
  level:
    root: debug
spring:
  datasource:
    username: root
    password: Az789@At
    url: jdbc:mysql://81.70.63.153:3306/rework_demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver