pipeline {
    agent any
    options {
        //设置管道运行的超时时间，在此之后，Jenkins将中止管道
        timeout(time: 10, unit: 'MINUTES')
        // 失败重试次数
        retry(2)
        //输出时间戳
        timestamps()
    }
    stages {
        stage('package') {
            agent {
                docker {
                            image 'maven'
                            // 把依赖挂载导服务器上，不用每次打包都下依赖
                            //阿里环境配置挂进去 PS踩坑：这里注意，挂载进去的
                            // settings.xml 文件必须放在 .m2 文件夹下，不是放在 maven 的 conf 下面，那样不会生效
                            args '-v /root/.m2:/root/.m2  -v /data/maven/settings.xml:/root/.m2/settings.xml --entrypoint='
                }
            }
            steps {
                script{
                    echo "WORKSPACE：${env.WORKSPACE}"
                    echo "Branch：${env.NODE_NAME}"
                    if ("${env.NODE_NAME}" == "master") {
                        sh "sh package-prod.sh"
                    }
                }
            }
        }
        stage('build') {
            agent none
            steps {
                script{
                    echo "WORKSPACE：${env.WORKSPACE}"
                    echo "Branch：${env.NODE_NAME}"
                    if ("${env.NODE_NAME}" == "master") {
                        sh "sh build-prod.sh"
                    }
                }
            }
        }
    }
}